Repository MikeSchulze/gdUnit3, pull requests merged in 2021-07, with the labels that each got.

#107 GD-106: Fix using add_child on before() in test suites do not break the API
  addons/gdUnit3/src/core/GdUnitExecutor.gd
  addons/gdUnit3/test/core/GdUnitExecutorTest.gd
  addons/gdUnit3/test/core/resources/testsuites/TestSuiteFailAddChildStageBefore.resource
Labels: bug, critical

#114 Added "(successes/total)" counter to test suite display.
  addons/gdUnit3/src/core/event/GdUnitEvent.gd
  addons/gdUnit3/src/ui/parts/InspectorTreeMainPanel.gd
  addons/gdUnit3/test/ui/parts/InspectorTreeMainPanelTest.gd
Labels: documentation, enhancement

#115 GD-111: Update was failing on unpacking the zip on OS X11
  addons/gdUnit3/src/update/GdUnitUpdate.gd
  addons/gdUnit3/test/update/GdUnitUpdateTest.gd
  addons/gdUnit3/test/update/resources/update.zip
  project.godot
Labels: bug, critical

#119 GD-117: Fixed GdUnitInspector event handling for test-suites with same name
  addons/gdUnit3/src/network/GdSerde.gd
  addons/gdUnit3/src/ui/parts/InspectorTreeMainPanel.gd
  addons/gdUnit3/test/GdUnitTestResourceLoader.gd
  addons/gdUnit3/test/ui/parts/InspectorTreeMainPanelTest.gd
  addons/gdUnit3/test/ui/parts/resources/bar/ExampleTestSuiteA.resource
  addons/gdUnit3/test/ui/parts/resources/foo/ExampleTestSuiteA.resource
  addons/gdUnit3/test/ui/parts/resources/foo/ExampleTestSuiteB.resource
  addons/gdUnit3/test/ui/parts/resources/foo/ExampleTestSuiteC.resource
  project.godot
Labels: bug

#121 GD-120: Added time factor functionallity to scene runner to speedup scene testing
  addons/gdUnit3/src/core/GdUnitSceneRunner.gd
  gdUnit3-examples/RoomDemo3D/test/rooms/RoomWithDoorTest.gd
Labels: enhancement
